name: Run style checks

on: [pull_request]

jobs:
  style_checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f  # v2.3.4
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@73b9a8098aade40363e43af145303c23542ccb97  # v2.0.1
      with:
        activate-environment: ptplot-dev
        auto-activate-base: false
        auto-update-conda: true
        environment-file: environment.yml
    - name: Sanity Check
      run: |
        conda list
        conda info -e

    - name: Black
      run: |
        python -m black -l 120 --check ptplot/

    - name: flake8
      run: |
        python -m flake8 ptplot/