name: Run tests with tox

on:
  pull_request:
  schedule:
      - cron: '*/5 * * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f  # v2.3.4
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@73b9a8098aade40363e43af145303c23542ccb97  # v2.0.1
      with:
        auto-activate-base: true
        auto-update-conda: true
        activate-environment: ""
        channels: conda-forge
    - name: Install tox
      run: |
        conda install tox
    - name: conda info
      run: |
         conda info -e
    - name: conda list
      run: |
         conda list
    - name: Test with tox - conda
      run: |
        tox -c tox-conda.ini
    - name: Test with tox - pip
      run: |
        tox -c tox-pip.ini
