name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: ""
        channels: conda-forge
    - name: Install tox
      run: |
        conda install tox
    - name: conda info
      run: |
         conda info -e
    - name: conda list
      run: |
         conda list
    - name: Test with tox
      run: |
        tox -c tox.ini
