name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@5a4ac90  # v2.3.4
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@73b9a80  # v2.0.1
      with:
        auto-activate-base: true
        activate-environment: ""
        channels: conda-forge
    - name: Install tox
      run: |
        conda install tox
    - name: conda info
      run: |
         conda info -e
    - name: conda list
      run: |
         conda list
    - name: Test with tox - conda
      run: |
        tox -c tox-conda.ini
    - name: Test with tox - pip
      run: |
        tox -c tox-pip.ini
